### ISSUE TITLE
Use CSS vars

### ISSUE THREAD

**Issue by kujiu** [isso-comments/isso#655]
CSS vars are really great. It'll be good to have some vars to define colors, with a standard CSS defining defaults like this:

``` css
:root {
   --issoInputFg: #000;
   --issoInputBg: #fff;
}

... input {
   color: var(--issoInputFg);
   background-color: var(--issoInputBg);
}
```

So, if we want to change color without define a complete CSS for ISSO, we just have to do things like that in the CSS of a website:
``` css
#page {
   --issoInputFg: #111;
   --issoInputBg: #aaa ;
}
@media(--prefers-color-scheme: dark) {
   #page {
      --issoInputFg: #fff;
      --issoInputBg: #000;
   }
}
```
It's easier and more flexible. This works on all current major browsers.

**Comment by kujiu** [comment]
If you think it's a good idea, I can do a proof of concept.

**Comment by vincentbernat** [comment]
IMO, you need to keep compatibility with IE10 (or at least IE11). As for a dark mode, only the forms need to be styled as everything else is mostly inherited from the main style. So, you could get what you want with:

```css
:root {
   --issoInputFg: #000;
   --issoInputBg: #fff;
}

... input {
   color: #000;
   color: var(--issoInputFg);
   background-color: #fff;
   background-color: var(--issoInputBg);
}
```

It's a small repetition as there shouldn't be many values.
